[package]
name = "tetra-pdus"
version.workspace = true
edition.workspace = true

[dependencies]
tetra-core = { workspace = true }
tetra-saps = { workspace = true }
tetra-config = { workspace = true }
tracing = { workspace = true }
